### ISSUE TITLE
Cannot upgrade to 0.4.0

### ISSUE THREAD

**Issue by mertalev** [tensorchord/pgvecto.rs#616] opened 2024-11-19 20:27 UTC
Hi, I'm testing the recent 0.4.0 release. It doesn't seem possible to use `ALTER EXTENSION UPDATE` to go from 0.2.0 or 0.3.0 to 0.4.0.

When running `ALTER EXTENSION vectors UPDATE TO '0.4.0';`, I get this error: `extension "vectors" has no update path from version "0.3.0" to version "0.4.0"`.

Edit: I see you're already working on it, so I'll just leave this as a tracking issue.

**Comment by GordonFreemanK** [comment] 2024-11-21 00:24
I had this issue yesterday on `tensorchord/pgvecto-rs-binary:pg14-v0.4.0-amd64` . Today with the latest version on the same tag (digest [7f61d2c8afbc](https://hub.docker.com/layers/tensorchord/pgvecto-rs-binary/pg14-v0.4.0-amd64/images/sha256-7f61d2c8afbc1726ffaf06b07984490ec2eaf09c2498cef3e7b367a8f78511a5?context=explore)) this issue doesn't seem to be there. I do get this though:

```
ERROR:  cannot change name of input parameter "_typmod"
HINT:  Use DROP FUNCTION _vectors_cast_array_to_vecf32(real[],integer,boolean) first. 

SQL state: 42P13
```

**Comment by xieydd** [comment] 2024-11-21 02:47
cc @cutecutecat

**Comment by cutecutecat** [comment] 2024-11-21 03:20
Hello, we are working on this issue:

> extension "vectors" has no update path from version "0.3.0" to version "0.4.0"

This error happens from an wrongly packaged version `0.4.0` at about 11/20 09:00 GMT+8 uploaded into dockerhub. And it has been fixed with new image now. Please force pull or redownload it you encounter the issue. It would be fine.

> Use DROP FUNCTION _vectors_cast_array_to_vecf32(real[],integer,boolean) first. 

The error is located. This is caused by a conflict signature from an `v0.2.1`, it would happen only if you installed `v0.2.1` and upgrade to `v0.3.0` and then `v0.4.0`. We will update a patch soon with a new packaged `v0.4.0`.

**Comment by cutecutecat** [comment] 2024-11-22 01:14
Hello, @GordonFreemanK  

The error of `Use DROP FUNCTION _vectors_cast_array_to_vecf32(real[],integer,boolean) first.` is fixed in the lastest `v0.4.0`. Welcome to have a try, please force pull or redownload the installer `deb` / `image`.

This issue will be hold for a week before it is closed, any problems about install / upgrade to `v0.4.0` can be append to comment here.

**Comment by GordonFreemanK** [comment] 2024-11-22 09:16
Hello! Thanks for the quick turnaround. I am now getting the following error (let me know if you'd like me to open a new issue as I don't think these are related):

```
ERROR:  index public.clip_index depends on operator class vector_cos_ops for access method vectors
index public.face_index depends on operator class vector_cos_ops for access method vectorscannot drop operator class vector_cos_ops for access method vectors because other objects depend on it 

ERROR:  cannot drop operator class vector_cos_ops for access method vectors because other objects depend on it
SQL state: 2BP01
Detail: index public.clip_index depends on operator class vector_cos_ops for access method vectors
index public.face_index depends on operator class vector_cos_ops for access method vectors
Hint: Use DROP ... CASCADE to drop the dependent objects too.
```

**Comment by cutecutecat** [comment] 2024-11-22 11:45
> Hello! Thanks for the quick turnaround. I am now getting the following error (let me know if you'd like me to open a new issue as I don't think these are related):
> 
> ```
> ERROR:  index public.clip_index depends on operator class vector_cos_ops for access method vectors
> index public.face_index depends on operator class vector_cos_ops for access method vectorscannot drop operator class vector_cos_ops for access method vectors because other objects depend on it 
> 
> ERROR:  cannot drop operator class vector_cos_ops for access method vectors because other objects depend on it
> SQL state: 2BP01
> Detail: index public.clip_index depends on operator class vector_cos_ops for access method vectors
> index public.face_index depends on operator class vector_cos_ops for access method vectors
> Hint: Use DROP ... CASCADE to drop the dependent objects too.
> ```

This is the expected behavior. The operator class is rewritten to support distance pushdown in v0.4.0, so we cannot keep the old scheme of it.

As a result, any indexes that depend on a vector operator class cannot be retained between updates. Any existing vector index must be dropped and rebuilt, sorry for the inconvenience.

**Comment by GordonFreemanK** [comment] 2024-11-22 12:41
No worries, I can do that. Thanks a lot for your quick replies!

**Closed** 2024-12-14 14:17 UTC
Labels: type/question 🙋, type/maintenance 🚧

**Comment by dasunsrule32** [comment] 2025-01-02 17:45
@cutecutecat not great at writing SQL scripts, could the docs be updated for this? Trying to upgrade as well and am getting:

```
ALTER EXTENSION vectors UPDATE;

ERROR:  index public.clip_index depends on operator class vector_cos_ops for access method vectors
index public.face_index depends on operator class vector_cos_ops for access method vectorscannot drop operator class vector_cos_ops for access method vectors because other objects depend on it 

ERROR:  cannot drop operator class vector_cos_ops for access method vectors because other objects depend on it
SQL state: 2BP01
Detail: index public.clip_index depends on operator class vector_cos_ops for access method vectors
index public.face_index depends on operator class vector_cos_ops for access method vectors
Hint: Use DROP ... CASCADE to drop the dependent objects too.
```

https://docs.vectorchord.ai/admin/upgrading.html

**Comment by dasunsrule32** [comment] 2025-01-02 17:53
Was able to figure it out I think:
```
DROP INDEX face_index;
DROP INDEX clip_index;

ALTER EXTENSION vectors UPDATE;
```

**Comment by cutecutecat** [comment] 2025-01-03 07:03
> @cutecutecat not great at writing SQL scripts, could the docs be updated for this? Trying to upgrade as well and am getting:
> 
> ```
> ALTER EXTENSION vectors UPDATE;
> 
> ERROR:  index public.clip_index depends on operator class vector_cos_ops for access method vectors
> index public.face_index depends on operator class vector_cos_ops for access method vectorscannot drop operator class vector_cos_ops for access method vectors because other objects depend on it 
> 
> ERROR:  cannot drop operator class vector_cos_ops for access method vectors because other objects depend on it
> SQL state: 2BP01
> Detail: index public.clip_index depends on operator class vector_cos_ops for access method vectors
> index public.face_index depends on operator class vector_cos_ops for access method vectors
> Hint: Use DROP ... CASCADE to drop the dependent objects too.
> ```
> 
> https://docs.vectorchord.ai/admin/upgrading.html

Sorry about that, I would add this in Q&A chapter in our document soon. Yes, we need to drop all the indexes before upgrade.
